/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chat.rest.api;

import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.Test;

import com.google.gson.Gson;

import chat.rest.api.ChatBot.API;
import chat.rest.api.service.core.ChatBotService;
import chat.rest.api.service.core.VelocitySupport;

public class ImageGenTest {
	@Test
	public void testApp() throws Exception {
		ChatBotService newBotService = ChatBot.newBotService(API.GTP_3_5);

		//chatgpt template binding
		String message = VelocitySupport.toString(new File("scripts/chat_gpt/image_gen/image_gen"),
				Map.of("content", "귀여운 고양이를 그려줘", "language", "Korean"));

		System.out.println("#################");
		System.out.println(message);
		System.out.println("#################");
		String send = newBotService.send(message);
		System.out.println("#################");
		System.out.println(send);
		System.out.println("#################");
		Gson gson = new Gson();
		HashMap fromJson = gson.fromJson(send, HashMap.class);
		System.out.println(((Map) ((Map) ((List) fromJson.get("choices")).get(0)).get("message")).get("content"));

	}
}
