/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chat.rest.api;

import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;

import chat.rest.api.ChatBot.API;
import chat.rest.api.service.core.ChatBotService;
import chat.rest.api.service.core.VelocitySupport;

public class App2 {

	public static void main(String[] args) throws Exception {}
}
